openapi: 3.0.1

info:
  title: ainize-tensorflowtts-eng-swagger
  description: |
    Convert english text into a speech
    ---
      How to use:
      * Select feature_generator and vocoder
      * Input text
      * Execute and wait little time
  contact:
    name: Ainizer - Sangil Park
  version: "0.1"
  license:
    name: "Apache License Version 2.0"
    url: https://github.com/psi1104/TensorFlowTTS/blob/tts-english/LICENSE

servers:
  - url: https://tts-english-tensor-flow-tts-psi1104.endpoint.ainize.ai/

paths:
  /predict:
    post:
      requestBody:
        required: true
        description: "Convert english text into a speech"
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                feature_generator:
                  type: string
                  enum: [TACOTRON, FASTSPEECH, FASTSPEECH2]
                vocoder:
                  type: string
                  eunm: [MELGAN, MELGAN-STFT, MB-MELGAN]
                input_text:
                  type: string

      responses:
        '200':
          description: success
          content:
            audio/wav:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request

        '500':
          description: Server side error